name: Deploy build to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      run: |
        git config --global user.name 'Andrii Bondariev'
        git config --global user.email 'andreybond13@gmail.com'
        git clone https://github.com/andreasblaze/andreasblaze.github.io.git && cd andreasblaze.github.io
        git checkout main
        # Safely remove the contents of the current directory without deleting the .git directory or other hidden files
        find . -maxdepth 1 ! -name '.git' ! -name '.' ! -name '..' -exec rm -rf {} \;
        # Copy build directory contents to the repo root
        cp -a ../build/* ./
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}